version: "1"
services:
  - type: web
    name: TourWeaver
    runtime: node
    repo: https://github.com/luiisrodriguez1996-sys/TourWaver
    plan: starter
    region: virginia
    buildCommand: npm install; npm run build
    startCommand: npm run start
    autoDeployTrigger: "off"
    envVars:
      - key: PORT
        value: 10000
